spring:
  application:
    name: helpdesk
  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk_db
    username: user
    password: passtheword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs